### PR TITLE
Add best of cubician samples

### PR DESCRIPTION
**Pull request by iansannar**
Added the best samples from my Cubician 7k and 10k sample packs. I made these and they are CC0. This pull request includes a small amount of acoustic drum samples and foley.

## ⚠️ Issues
- [x] Samples are not consistently normalized
- [x] Some samples have a small amount of start silence

### CODE REVIEW

**Comment by Sawuare** [comment]
Hi, @iansannar.
We do not accept assets by pull requests.
Please send them to #assets on Discord for them to be reviewed then added.

**Comment by Sawuare** [comment]
I think `Sampled Snare 1` and `Tongue Click 4` are not that good and should be dropped.
I approve of the rest.

**Comment by iansannar** [comment]
image

**Comment by iansannar** [comment]
If this PR needs to be edited, closed, or merged, let's do that.

**Pull request merged**
