### PR TITLE
Categorized Wontolla percussion, started adding self-made sample pack

### PR DESCRIPTION
**Pull request by QrchackOfficial**
I created a Drums/Kicks folder tree for the sample library to be included with LMMS.

Here's some proof for the kick (to show it was self-made):

Of course, the new sample provided (`kick01.wav`) is hereby licensed under the [CC0 1.0 Universal (CC0 1.0)  License](https://creativecommons.org/publicdomain/zero/1.0/)

Also, kick samples from "Wontolla percussion" (as they are legally cleared, but unsorted) are moved to the same Drums/Kicks folder.

I'm working on more samples as well, requests are very much welcome.

Preview of the sample (`kick01.wav`):
https://clyp.it/etpcc3uw?token=10dd70965c99208aa750df528f55d59a

### CODE REVIEW

**Comment by SirBothersome** [comment]
Why hello there.  It's nice to see somebody else here. I checked out your kick, and there appears to be a sizeable portion of predelay before the actual kick. You can trim that out down to the last sample with audacity. Also, all new samples are going to be stereo flacs, exported at the highest quality. I'd appreciate it if you cloned my samples repo [https://github.com/SirBothersome/samples](url) so that we're not doing the same stuff twice. Good luck
(@tresf, should this be merged with #25 ?)

**Comment by QrchackOfficial** [comment]
Any reason for FLAC (apart from "just because we can")? WAV is the standard for samples, eg. on Windows FLAC requires a codec to be installed up till Windows 10, and with 50kB files it's not like we're gaining much by using compression.

**Comment by QrchackOfficial** [comment]
Also, the `kick01.wav` from repo has no predelay at all, it's probably because of 128kbps MP3 conversion after uploading to Clyp. Here's the waveform for it:

**Comment by SirBothersome** [comment]
> Any reason for FLAC (apart from "just because we can")?

Admin decided that. I don't have the time to find the issue reference ATM, but basically the quality is better.

**Comment by QrchackOfficial** [comment]
It can't be. WAV is a one-to-one copy, just a stream of bits as they come in. FLAC is just compressing that stream with lossless compression. You get exactly the same quality (unless you tell FLAC to downgrade for better file size).

**Comment by tresf** [comment]
> Any reason for FLAC

Consistency, really.  Larger samples can benefit and it offers a unified format.

> FLAC requires a codec to be installed up till Windows 10

Same argument can be made for OGG, really.  The native OS support isn't overly relevant so as long as the DAW shims with playback ability out of the box.

**Comment by Umcaruje** [comment]
>I'd appreciate it if you cloned my samples repo https://github.com/SirBothersome/samples so that we're not doing the same stuff twice. Good luck
(@tresf, should this be merged with #25 ?)

Actually, I think that multiple PR's can be a really nice solution for this problem, as long as all of us communicate. Doing this in bite sizes and avoiding monster PR's is the way to go imho

**Comment by SirBothersome** [comment]
> Actually, I think that multiple PR's can be a really nice solution for this problem, as long as all of us communicate. Doing this in bite sizes and avoiding monster PR's is the way to go imho

@Umcaruje, If you say so. I was actually saying that because #25 already contains similar kicks. I just wanted @QrchackOfficial to see what I've done so that we aren't making redundant work.

**Comment by SirBothersome** [comment]
> I created a Drums/Kicks folder tree for the sample library to be included with LMMS.

@QrchackOfficial, I think it would be better to have folder trees of sample collections a la Hydrogen. (e.g. acoustic samples together, 808 samples together, electronic samples together etc.) IMO, there's more functionality there.

**Comment by QrchackOfficial** [comment]
@SirBothersome Possibly, there's still the issue of things like Electro directory having everything plus the kitchen sink. Maybe at least put it in Drums, then Electric/Acoustic? So we could have bass oneshots and whatnot separately.

**Comment by SirBothersome** [comment]
> @SirBothersome Possibly, there's still the issue of things like Electro directory having everything plus the kitchen sink

That's basically how our current directory system is. I've yet to hear anyone complain.

**Comment by SirBothersome** [comment]
@QrchackOfficial, can I message you via G+? This is going to involve a lot of discussion methinks.

**Comment by QrchackOfficial** [comment]
I hardly ever use G+. Email/Twitter/Slack/Skype would be the way to get to me (in descending reply time order)

**Comment by SirBothersome** [comment]
Closing this. Repo has been largely restructured, and I have not heard from @QrchackOfficial in a bit on the new samples,

**Pull request closed without merging**
